// landing/egypt_data.js - بيانات مصر الرسمية من Speedaf
const EGYPT_CITIES_EN_TO_AR = {
    'Sharqia': 'الشرقية',
    'Cairo': 'القاهرة',
    'Giza': 'الجيزة', 
    'Alexandria': 'الإسكندرية',
    'Dakahlia': 'الدقهلية',
    'Gharbia': 'الغربية',
    'Monufia': 'المنوفية',
    'Qalyubia': 'القليوبية',
    'Behira': 'البحيرة',
    'Ismailia': 'الإسماعيلية',
    'Port Said': 'بورسعيد',
    'Suez': 'السويس',
    'Damietta': 'دمياط',
    'Aswan': 'أسوان',
    'Asyut': 'أسيوط',
    'BeniSuef': 'بني سويف',
    'Faiyum': 'الفيوم',
    'Minya': 'المنيا',
    'Qena': 'قنا',
    'Red Sea': 'البحر الأحمر',
    'New Valley': 'الوادي الجديد',
    'Matrouh': 'مطروح',
    'North Sinai': 'شمال سيناء',
    'South Sinai': 'جنوب سيناء',
    'Luxor': 'الأقصر',
    'Sohag': 'سوهاج'
};

const EGYPT_CITY_AREAS = {
    'Sharqia': ['Zagazig', 'Minya El Qamh', 'Mashtol Al Souq', 'Hihya', 'El Qurein', 'El Qanayat', 'El Ibrahimiya', 'Diyarb Negm', 'Bilbeis', 'Abu Hammad'],
    'Cairo': ['Downtown', 'Nasr City', 'New Cairo', 'Maadi', 'Helwan', 'Shorouk', 'Ain Shams', 'El Marg', 'El Nozha', 'Masr El Gadida', 'Heliopolis', 'Zamalek', 'Dokki', 'Mohandisen', 'Manial', 'Faisal', 'Haram', 'Hadayk Ahram', 'Zayton', 'El Basatin', 'El Katameya', 'El Mokattam'],
    'Giza': ['Faisal', 'Haram', 'Hadayk Ahram', 'Dokki', 'Mohandisen', 'Imbaba', 'Bolak Al Dakrour', 'Al Agouzah', 'Warak', 'Omrania', 'Kerdasa', 'Abou Rawash'],
    'Alexandria': ['Al-agamy', 'Alex', 'Moharram Bek', 'Sidi Gaber', 'El-Raml', 'Montaza', 'Al Mamurah', 'Abu Qir', 'El-Agamy', 'Dekhela', 'Borg al arab', 'Smouha', 'Sidi Bishr', 'Miami', 'Stanley', 'Camp Shezar', 'Cleopatra', 'Gleem', 'Laurent', 'Mandara', 'Asafra', 'Al Anfoushi', 'Al Attarin', 'Al Gomrok', 'Bab Sharqi', 'Karmouz'],
    'Dakahlia': ['El Mansoura', 'Mit Ghamr', 'Talkha', 'Aga', 'El-Senbellawein', 'Belqas', 'Gamasa'],
    'Gharbia': ['Tanta', 'El Mahalla El Kubra', 'Zefta', 'Kafr El Zayat', 'Basyoun', 'Qutur', 'El Santa'],
    'Monufia': ['Shibin el Kom', 'Menouf', 'Tala', 'El Sadat City', 'Ashmoun', 'El Bagour', 'Quwaysna'],
    'Qalyubia': ['Banha', 'Tukh', 'Shibin El Qanater', 'Qalyub', 'Kafr Shukr', 'El Qanater El Khayreya'],
    'Behira': ['Damanhour', 'Kafr El Dawwar', 'Rasheed', 'Edku', 'Abu Hummus', 'Itay Al Barud', 'Shubrakhit', 'Mahmoudiyah', 'Kom Hamada', 'Al Delengat', 'Badr'],
    'Ismailia': ['Ismailia', 'Fayed', 'El Qantara', 'Tell El Kebir', 'Abu Suwir', 'Abu Sultan'],
    'Port Said': ['Port Said', 'Port Fuad', 'El Dawahy', 'El Zohur', 'El Sharq', 'Al Ganoub'],
    'Suez': ['Suez', 'Port Tawfik', 'Arbaeen', 'Attaka', 'Faisal', 'Ganayen'],
    'Damietta': ['Damietta', 'New Damietta', 'Ras El Bar', 'Kafr Saad', 'Kafr El Battikh', 'Faraskur'],
    'Aswan': ['Aswan city', 'New Aswan', 'Kom Umbu', 'Edfu', 'Draw', 'Nasr City', 'Al Gaafrah'],
    'Asyut': ['Asyut city', 'New Asyut', 'Abnub', 'Abu Tij', 'El-Ghanayem', 'Manfalut', 'Sahel Selim'],
    'BeniSuef': ['Beni Suef city', 'New Beni Suef', 'Biba', 'Al Fashn', 'Ihnasiya', 'Sumusta', 'Nasser'],
    'Faiyum': ['Faiyum center', 'New Faiyum', 'Ibsheway', 'Itsa', 'Sinnuris', 'Tamiyyah', 'Kufur an Nil'],
    'Minya': ['Minya City', 'New Menya', 'Beni Mazar', 'Matay', 'Maghagha', 'Samalut', 'Abu Qurqas'],
    'Qena': ['Qena', 'New Qena', 'Nagaa Hammadi', 'Dishna', 'Qus', 'Qift', 'Naqada'],
    'Red Sea': ['Hurghada', 'Sharm El-Sheikh', 'Marsa Alam', 'Safaga', 'El Qusair', 'Ras Gharib'],
    'New Valley': ['Kharga', 'Dakhla', 'Farafra', 'Baris'],
    'Matrouh': ['Marsa Matruh', 'El-Alamein', 'El Hamam', 'Sidi Barrani', 'Sallum', 'El Dabaa'],
    'North Sinai': ['El Arish', 'Sheikh Zuweid', 'Rafah', 'Bir al-Abd'],
    'South Sinai': ['Sharm El-Sheikh', 'Dahab', 'Nuweiba', 'Taba', 'Ras Sedr', 'Abu Redis', 'Saint Catherine'],
    'Luxor': ['Luxor City', 'New Luxor', 'Armant', 'Esna', 'Al Qarnah', 'Al Madamoud'],
    'Sohag': ['Sohag', 'New Sohag', 'Akhmim', 'New Akhmim', 'Tahta', 'Tima', 'Al Minshah']
};

// ترجمة المناطق من الإنجليزية إلى العربية (نماذج فقط)
const AREA_TRANSLATIONS = {
    'Zagazig': 'الزقازيق',
    'Maadi': 'المعادي',
    'Nasr City': 'مدينة نصر',
    'New Cairo': 'القاهرة الجديدة',
    'Dokki': 'الدقي',
    'Mohandisen': 'المهندسين',
    'Sidi Gaber': 'سيدي جابر',
    'El-Raml': 'الرمل',
    'Al Mamurah': 'المعمورة',
    'El-Agamy': 'العجمي'
};
